### ISSUE TITLE
Transform Yaml Configurations into Rst Code

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-screenshots#134]
Input: 

```
EXT:
    type: container
    description: 'Extension Installation'
    items:
        allowGlobalInstall:
            type: bool
            description: 'If set, global extensions in typo3/ext/ are allowed to be installed, updated and deleted etc.'
        allowLocalInstall:
            type: bool
            description: 'If set, local extensions in typo3conf/ext/ are allowed to be installed, updated and deleted etc.'
        excludeForPackaging:
            type: list
            description: 'List of directories and files which will not be packaged into extensions nor taken into account otherwise by the Extension Manager. Perl regular expression syntax!'
BE:
    type: container
    description: 'Backend'
    items:
        languageDebug:
            type: bool
            description: 'If enabled, language labels will be shown with additional debug information.'
        fileadminDir:
            type: text
            description: 'Path to the primary directory of files for editors. This is relative to the public web dir, DefaultStorage will be created with that configuration, do not access manually but via <code>\TYPO3\CMS\Core\Resource\ResourceFactory::getDefaultStorage().</code>'
        lockRootPath:
            type: text
            description: 'This path is used to evaluate if paths outside of public web path should be allowed. Ending slash required!'
        userHomePath:
            type: text
            description: 'Combined folder identifier of the directory where TYPO3 backend-users have their home-dirs. A combined folder identifier looks like this: [storageUid]:[folderIdentifier]. Eg. <code>2:users/</code>. A home for backend user 2 would be: <code>2:users/2/</code>. Ending slash required!'
     ```

desired output:
```
.. confval:: lockRootPath

   :type: text
   :Scope: BE

   Combined folder identifier of the directory where TYPO3 backend-users have their home-dirs. A combined folder identifier looks like this: [storageUid]:[folderIdentifier]. Eg. :code:'2:users/'. A home for backend user 2 would be:  :code:'2:users/2/'. Ending slash required!
```

**Comment by alexander-nitsche** [comment]
Mh, the example transformation looks wrong or too complicated to get what you want to transform how.

**Comment by linawolf** [comment]
So should we close this request as impossible or find a better headline? What do you suggest?

**Comment by alexander-nitsche** [comment]
No, i just need more information about this transformation:

How to get from 
```
BE:
    type: container
    description: 'Backend'
    items:
        ..
        lockRootPath:
            type: text
            description: 'This path is used to evaluate if paths outside of public web path should be allowed. Ending slash required!'
```
to
```
.. confval:: lockRootPath

   :type: text
   :Scope: BE

   Combined folder identifier of the directory where TYPO3 backend-users have their home-dirs. A combined folder identifier looks like this: [storageUid]:[folderIdentifier]. Eg. :code:'2:users/'. A home for backend user 2 would be:  :code:'2:users/2/'. Ending slash required!
```
and in which special scenario is this used?
